utils/shuffle_tables.c
This is so far a standalone utility that prints the decoder shuffle table to stdout, trying to match the existing one in the decoder source.  There's also an encoder shuffle table generator, and the lengths table.
The subroutines inside generate the actual shuffle table as the same uint8_t array used by the decoder, so they could be used to instantiate the table instead of the static declaration.
=> decoder and encoder shuffle table generator

src/streamvbyte.c
This works on clang-4.0, but the pextrb intrinsic throws errors on gcc:
/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:443:27: error: selector must be an integer constant in the range 0..15
return (unsigned char) __builtin_ia32_vec_ext_v16qi ((__v16qi)__X, __N);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I believe this is simply wrong, as the arg is a const int, but not a constant.  
Performance on clang is *exactly* the same:  
kendall@skylake:~/streamvbyte$ ./perf
time = 0.036000  1388888960.000000 uints/sec
compsize=1281422 compsize2 = 1281422
Compressed 500000 integers down to 1281422 bytes.
=> decode without length table

include/streamvbyte.h
The include guard does not use the typical style, which is derive its name from the file. 
This causes a conflict with https://github.com/lemire/MaskedVByte/blob/master/include/varintdecode.h
=> Updated include guard

src/streamvbyte.c
SSE4_1 PEXTRB is faster & cleaner than manually extracting bytes with
movq/shr/and
=> Encoder: use PEXTRB

AUTHORS, CMakeLists.txt, README.md
Currently, there is no option to install other than to
install the library, headers in a global scope. This doesn't play
nice with other build systems.
With this file a user can simply do:
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX:PATH=/path/to/install
make -j8 install
```
In addition, I added tests/unit to the unit test framework of cmake
so that you can do ctest -V and you would get:
```
Test project /home/agallego/workspace/streamvbyte/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
Start 1: unit
1: Test command: /home/agallego/workspace/streamvbyte/build/unit
1: Test …
```
=> Add CMakeLists.txt to streamvbyte

CMakeLists.txt
While integrating into another cmake project via add_subdirectory()
the target `check` might already be defined by a parent directory.
In addition, on a parent project when you run its unit tests
you don't want child project unit tests to run
For example, this won't build the unit tests:
```sh
cmake -DSTREAMVBYTE_ENABLE_TESTS=OFF .. 
```
=> CMake: allow parent project to disable unit tests for streamvbyte

CMakeLists.txt
For cmake transitive builds, specifying the include directories
on the targets themselves ensures that parent projects do not
have to hack around include_directory() paths. These symbols
get exported transparently to other cmake-based projects
=> cmake: use target_include_directory for libstreamvbyte

CMakeLists.txt
Turn on position independent code so a static library can  [packaged](https://github.com/iiSeymour/pystreamvbyte/issues/2) with the Python bindings.
=> Turn on position independent code

CMakeLists.txt
`sys/resource` does not exist on windows: https://pubs.opengroup.org/onlinepubs/7908799/xsh/sysresource.h.html
`__restrict__` is instead `__restrict` on msvc.
=> Msvc 2017 build

.gitignore, include/streamvbyte.h, tests/unit.c
For #32 - please read for context. Sometimes it's better to trade off encoding runtime for reduced peak memory allocation.
Fixes https://github.com/lemire/streamvbyte/issues/32
=> Adds optional function to compute required memory

.github/workflows/ubuntu.yml, .github/workflows/vs.yml, CMakeLists.txt, src/streamvbyte_zigzag.c, tests/unit.c
This adds undefined sanitizer tests.
=> Adding undef. tests.

src/streamvbytedelta_x64_decode.c
clang-cl defines __m128i as a pair of long long values. Setting it to `{8, 9, ...}` results in a warning and resulting value of __m128i = `{8, 9}`
Fixes the following warning: 
streamvbytedelta_x64_decode.c(46,33): warning : excess elements in vector initializer [-Wexcess-initializers]
=> Fix __m128i init when building with clang-cl

CMakeLists.txt
* Fix `target_include_directories()` path 
* Reformat `CMakeLists.txt` with [gersemi](https://github.com/BlankSpruce/gersemi)
```cmake
target_include_directories(streamvbyte  PUBLIC ${PROJECT_SOURCE_DIR}/include)
```
Will not work after exporting the target and will make difficult to use streamvbyte as a cmake dependency
Replced by 
```cmake
target_include_directories(
streamvbyte
PUBLIC
$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/include>
)
```
=> Fix target_include_directories path

src/streamvbyte_isadetection.h
For me at least in VS2022 16.4, when using clang-cl (15.0), it does not build since some SSE3 or SSE4 intrinsics are being compiled, without including the headers that define them.
=> Fix build on clang-cl 15.0

CMakeLists.txt
`CMake` has own `BUILD_SHARED_LIBS` flag which allows to choose between static/shared library creation. So no need to specify it explicitly. Moreover it creates problems when using `stremvbyte` as a dependency.
=> Remove streamvbyte_static and explicit shared/static specification

include/streamvbyte.h, src/streamvbyte_encode.c, src/streamvbyte_x64_encode.c
I'm trying to use compressedbytes to get the allocation size beforehand but this turned out to be awfully slow and taking more time than just doing the (SIMD-accelerated) encoding itself.
This PR fixes that and does a few things:
- It makes scalar compressedbytes branchless so that it's less awful.
- It adds a SSE41 path for compressedbytes, reusing mask calculation from the encode path.
* Sorry, but there is no implementation for:
- ARM NEON (don't have a machine to test)
- 0124 path (don't have unit tests and the code structure is somewhat different).
=> Add SSE41 path for streamvbyte_compressedbytes.

src/streamvbyte_x64_encode.c, src/streamvbytedelta_x64_encode.c
This pull request fixes two typos, no functional changes.
=> Fix some typos

.github/workflows/macos.yml, .github/workflows/ubuntu20.yml, .github/workflows/ubuntu22.yml, .github/workflows/vs.yml, .github/workflows/vs16.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.5.2
> - Fix api endpoint for GHES
>
> ## v3.5.1
> - Fix slow checkout on Windows
>
> ## v3.5.0
> - Add new public key for known_hosts
>
> ## v3.4.0
> - Upgrade codeql actions to v2
> - Upgrade dependencies
> - Upgrade @actions/io
>
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - …
=> Update actions/checkout in GitHub Actions workflows to v3

CMakeLists.txt
remove `set(CMAKE_MACOSX_RPATH OFF)` to allow installing relocatable shared lib for macOS
=> CMake: relocatable shared lib on macOS

CMakeLists.txt
dll goes in bin folder by convention.
=> CMake: fix installation layout of dll for windows

CMakeLists.txt, Makefile, README.md, include/streamvbyte.h, include/streamvbytedelta.h, src/streamvbyte_0124_decode.c, src/streamvbyte_arm_decode.c, src/streamvbyte_decode.c, src/streamvbyte_encode.c, tests/unit.c
This PR adds 2 new functions to validate encoded streams. These are useful when loading data from untrusted sources (disk, network, etc...) since it's typically trivial to change the uncompressed size that's stored alongside the
encoded data. This has caused crashes for us where the decode functions have trusted the corrupted size and ended up reading into an unmapped page.
I was split between doing it this way or adding a `streamvbyte_decode_safe()` which also took in the size of the input, but this appeared to be the simpler of the two for error handling (at the expense of having to traverse the data twice if you need to check and then decode).
Also as part of this PR I've fixed up the ASAN build so that it links (which caught a leak in the tests), fixed the Makefile build (presumably …
=> Add validation functions and fixup sanitizer build

CMakeLists.txt, Makefile, src/streamvbyte_decode.c, src/streamvbyte_encode.c, src/streamvbyte_isadetection.h, tests/unit.c
Fixes https://github.com/fast-pack/streamvbyte/issues/74
=> simpler ARM detection
